### ISSUE TITLE
Pixel XL gets stuck during boot

### ISSUE THREAD

**Issue by Namelesswonder** [TrebleDroid/treble_experimentations#10]
### Current Behavior:
Pixel XL gets stuck while booting with several services failing and credstore crashing.
Device doesn't reboot, and keeps on trying to restart the services and start credstore.
  
### Smartphone:
 - Device: Pixel XL
 - Firmware: qp1a.191005.007.a3
 - Build Flavor: system-td-arm64-ab-vndklite-vanilla
 - Version: android_13.0.0_r24 ci-20230131

### Additional context:
None of the TD releases going back to android_13.0.0_r8 ci-20221107 boot.

### Logcat:
[logcat.log](https://github.com/TrebleDroid/treble_experimentations/files/10728499/logcat.log)

Logcat was stopped after it began the loop of credstore crashing and android.frameworks.sensorservice@1.0::ISensorManager/default not being found.

**Comment by phhusson** [comment]
Ok so the error is:
`04-07 03:40:16.041     0     0 E         : c3      1 EXT4-fs (sda35):
couldn't mount RDWR because of unsupported optional features (2000)`
Which I'm pretty sure I already fixed,though I don't quite remember how.

First, please confirm that you did a factory reset with stock
recovery. NOT fastboot erase userdata or fastboot format userdata. If
you use a TWRP use "Format data", not just "wipe all"

**Comment by Namelesswonder** [comment]
Well that was it.

I find it surprising that v416 didn't have any qualms with me doing a wipe from fastboot but the Android 13 releases do.
